version: '2'

services:
  drone-server:
    image: drone/drone:alpine
    ports:
      - 8000:8000
      - 9000
    volumes:
      - /home/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://ait-akkache-soufiane.info:8000
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=377693676b54e453db6c
      - DRONE_GITHUB_SECRET=168c63e998d0c457e5abda71756a6643c3cc4b02
      - DRONE_SECRET=secretKey

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=secretKey